### ISSUE TITLE
Error while using JDBC2S jar with PySpark

### ISSUE THREAD

**Issue by wizard-31** [AbsaOSS/Jdbc2S#23]
Hi Jdbc2S team,
Thank you so much for this repo.

I'm working on a personal project where I need to fetch real-time data from the Database using Spark Structured Streaming API. 
I tried 2 approaches listed below.

1. Downloaded the Jdbc2S jar and used it during SparkSession initiation.
`format = "za.co.absa.spark.jdbc.streaming.source.providers.JDBCStreamingSourceProviderV1"
spark = SparkSession.builder.config("spark.jars","./pathtoJar1, ./jdbc2s_2.11-1.2.0.jar").appName("StreamingCount").getOrCreate()`

When I try to execute the script, I get the following error.
"Traceback (most recent call last):
  File "SparkStreaming.py", line 14, in <module>
    count_sql = spark.readStream.format(format) \
  File "/Users/subramaniav1/Library/Python/3.8/lib/python/site-packages/pyspark/sql/streaming.py", line 454, in load
    return self._df(self._jreader.load())
  File "/Users/subramaniav1/Library/Python/3.8/lib/python/site-packages/py4j/java_gateway.py", line 1321, in __call__
    return_value = get_return_value(
  File "/Users/subramaniav1/Library/Python/3.8/lib/python/site-packages/pyspark/sql/utils.py", line 111, in deco
    return f(*a, **kw)
  File "/Users/subramaniav1/Library/Python/3.8/lib/python/site-packages/py4j/protocol.py", line 326, in get_return_value
    raise Py4JJavaError(
py4j.protocol.Py4JJavaError: An error occurred while calling o37.load.
: java.lang.NoClassDefFoundError: org/apache/spark/sql/sources/v2/DataSourceV2"

I use Python 3.8.9, Scala 2.12.15 and Spark 3.2.1

2. I tried to follow the steps mentioned in https://stackoverflow.com/a/72158761 where someone was able to modify and use this with PySpark. I modified the object JDBCStreamingSourceV1 in JDBCStreamingSourceV1.scala as mentioned, and the pom.xml with updated scala version and tried to rebuild the jar using Maven. 

I got build failure with the following error "java.io.InvalidObjectException: ReflectiveOperationException during deserialization"

It'd be of great help if you can help with steps to use this repo with Pyspark

**Comment by PRESFIL** [comment]
Looks like Scala version of your Spark installation not matches with Scala
version of this package. But this package not built for Scala versions other
than `2.11`.

Maybe you can downgrade Spark version for `2.4.8` to make this work correctly.

See #24 .
